# This is a basic workflow to help you get started with Actions

name: CI

env:
  OUTPUT_PATH: ${{ github.workspace }}
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: runner-1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install
      - name: Run addlock
        run: npm run addlock
      - name: Run copy script
        run: |
          New-Item -Path "C:\gitworkflowrunner" -ItemType Directory -Force
          Remove-Item -Path "C:\gitworkflowrunner\*" -Recurse -Force
          Copy-Item -Path "C:\Users\hello\actions-runner\_work\gitworkflowrunner\gitworkflowrunner\*" -Destination "C:\gitworkflowrunner" -Recurse
        shell: pwsh
      - name: Run removelock
        run: npm run removelock
